### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by arjung24** [Bizordec/vk-to-tgm#4]
It would be very much helpful if you made a video tutorial of deployment using VPS.

Any plan to make it deploy in Heroku??

Thanks for your great work 💗💗

**Comment by Bizordec** [comment]
1. Get any VPS with minimum 2GB RAM;
2. Git clone project there;
3. Follow the instructions in [README](https://github.com/Bizordec/vk-to-tgm#installation).

And that's it :)

Not sure how to deploy to Heroku, sorry.
